WIP: active directory support
SUSE/ha-sap-terraform-deployments pull request #521
Opened 2020-08-24 09:23 UTC by MalloZup

# description:

this PR is still on working progress, not worth to review right now since it will change

2020-08-26 20:05 UTC, MalloZup commented
![image](https://user-images.githubusercontent.com/10886597/91351197-2eb0f780-e7e8-11ea-99c0-ae4eefa79c27.png)

2020-09-01 08:44 UTC, MalloZup commented
why this is closed?

2020-09-01 08:57 UTC, stefanotorresi commented
my mistake! sorry!

2020-09-02 06:27 UTC, arbulu89 requested changes
@MalloZup In general it looks a good implementation. I added some small comments. And besides them:

We will need to figure it out how to deal with different role nodes (hana, netweaver, monitoring). I would assume that someone who is using AD, would like to have all the machines associated to this AD server, but obviously, not all the users should belong to all machines. Do we know how to do so?

2020-09-02 06:27 UTC, arbulu89 commented on libvirt/variables.tf
> +
Remove all of these new lines please.

2020-09-02 06:27 UTC, arbulu89 commented on libvirt/variables.tf
> +  description = "password for admin of domain"
The rest of the descriptions are started with capital letter. This should follow the rule

2020-09-02 08:00 UTC, MalloZup commented
I think if the admin wants to have granularity and fine acess control, 
for netweaver/etc, the solution can be that the AD admin create subdomain

`foo.test.hana`, `foo.test.netweaver` `foo.test.monitoring`. etc

i think we could create like a list of map in terraform where the user specify host/role to AD

in pseudo code
`hana: foo.test.hana`, `netweaver: foo.test.netweaver` etc
`hana_pdw` 
and by default if there is no map but a global domain, just join all machine to this

somehting in this direction

2020-09-02 10:46 UTC, MalloZup commented on salt/active_directory/setup.sls
> +      - tcsh
we don't need this will remove

2020-09-03 15:58 UTC, MalloZup commented on libvirt/variables.tf
> +  description = "password for admin of domain"
ok

2020-09-06 19:25 UTC, MalloZup commented
```module.netweaver_node.module.netweaver_provision.null_resource.provision[2] (remote-exec): [ERROR   ] Command '['groupmod', '-g', 2002, 'sapsys']' failed with return code: 10
module.netweaver_node.module.netweaver_provision.null_resource.provision[2] (remote-exec): [ERROR   ] stdout: groupmod: group 'sapsys' does not exist in /etc/group
module.netweaver_node.module.netweaver_provision.null_resource.provision[2] (remote-exec): [ERROR   ] retcode: 10
``` 
seems in netweaver we hardcoded groups with `groupmod`

2020-09-07 08:56 UTC, stefanotorresi commented
> seems in netweaver we hardcoded groups with `groupmod`

what salt state was this in?

2020-09-07 09:34 UTC, MalloZup commented
@stefanotorresi  it is an upstream call group.present which we call on netweaver formula.

However due the early stage of the `netweaver` AD implementation/integration I need to check if it is the culprit or is an `error` we have just because of that.

2020-10-19 13:04 UTC, MalloZup commented
Closing this since we will just offer some documentation which I'm working with thomas. is ok to close

2020-10-19 13:04 UTC, closed without merging