Run iscsi-init service to create initiatorname.iscsi file
SUSE/ha-sap-terraform-deployments pull request #525
Opened 2020-09-01 13:20 UTC by arbulu89

After open-iscsi has been upgraded to 2.1.2 version, the initiatorname.iscsi file is not shipped by default,and it's created with iscsi-init service.

More information in: https://build.opensuse.org/package/view_file/network/open-iscsi/open-iscsi.changes?expand=1

The new version has only been shipped to SLE15SP2, that's why the filter is set.

**PD: This change should be backported to master branch at some point if we don't plan a new release soon, as it has the same impact there**

2020-09-01 13:25 UTC, stefanotorresi requested changes
@arbulu89 I think we should target this change to master and then forward-port it to develop.

2020-09-01 13:25 UTC, stefanotorresi commented on salt/cluster_node/ha/iscsi_initiator.sls
> +{% if grains['osrelease_info'][0] == 15 and grains['osrelease_info'][1] == 2 %}
what happens with future versions?

2020-09-01 13:27 UTC, arbulu89 commented on salt/cluster_node/ha/iscsi_initiator.sls
> +{% if grains['osrelease_info'][0] == 15 and grains['osrelease_info'][1] == 2 %}
> @arbulu89 I think we should target this change to master and then forward-port it to develop.

The things is that it wouldn't be a direct port. The applied change is even in different files, so the commit must be different I guess.

2020-09-01 13:28 UTC, arbulu89 commented on salt/cluster_node/ha/iscsi_initiator.sls
> +{% if grains['osrelease_info'][0] == 15 and grains['osrelease_info'][1] == 2 %}
> what happens with future versions?

Frankly, I don't even know what will happen in older versions... What I know now is that the new version only has been shipped in SLE15SP2, and not in the other versions.

2020-09-01 15:06 UTC, MalloZup commented on salt/cluster_node/ha/iscsi_initiator.sls
> +{% if grains['osrelease_info'][0] == 15 and grains['osrelease_info'][1] == 2 %}
an alternative approach would be

```
start_iscsi_init:
  module.run:
    - service.start:
      - name: iscsi-i
    - - check_cmd:
         '/usr/bin/true` (which always be true)

```
It might seems a bit ugly but on the other side we spare the `15sp3` and later checks maintenance.
```

2020-09-02 06:35 UTC, arbulu89 commented on salt/cluster_node/ha/iscsi_initiator.sls
> +{% if grains['osrelease_info'][0] == 15 and grains['osrelease_info'][1] == 2 %}
@MalloZup I don't understand what that command would help on. If it's always true, what is the benefit of using it?

2020-09-02 07:45 UTC, MalloZup commented on salt/cluster_node/ha/iscsi_initiator.sls
> +{% if grains['osrelease_info'][0] == 15 and grains['osrelease_info'][1] == 2 %}
the benefits is that it will run always and execute, nevertheless the distro. 

it is like `mkdir -p`            no error if existing, make parent directories as needed

2020-09-02 10:46 UTC, stefanotorresi commented on salt/cluster_node/ha/iscsi_initiator.sls
> +{% if grains['osrelease_info'][0] == 15 and grains['osrelease_info'][1] == 2 %}
@MalloZup as you said, it's a bit ugly: it would hide actual failures of the service, and our future selves would have a harder time understanding what's that for.

2020-09-02 14:09 UTC, stefanotorresi requested changes

2020-09-02 14:09 UTC, stefanotorresi commented on salt/cluster_node/ha/iscsi_initiator.sls
> +{% if grains['osrelease_info'][0] == 15 and (grains['osrelease_info']|length > 1 and grains['osrelease_info'][1] >= 2) %}
We still need to cover for version above 15, right?

2020-09-02 14:47 UTC, arbulu89 commented on salt/cluster_node/ha/iscsi_initiator.sls
> +{% if grains['osrelease_info'][0] == 15 and (grains['osrelease_info']|length > 1 and grains['osrelease_info'][1] >= 2) %}
Do we really need that? SLE16 (if this is the next release) won't come in year.

2020-09-02 14:48 UTC, arbulu89 commented on salt/cluster_node/ha/iscsi_initiator.sls
> +{% if grains['osrelease_info'][0] == 15 and (grains['osrelease_info']|length > 1 and grains['osrelease_info'][1] >= 2) %}
Change pushed in any case

2020-09-02 15:17 UTC, stefanotorresi commented on salt/cluster_node/ha/iscsi_initiator.sls
> +{% if grains['osrelease_info'][0] == 15 and (grains['osrelease_info']|length > 1 and grains['osrelease_info'][1] >= 2) %}
better safe than sorry :wink:

2020-09-02 15:34 UTC, stefanotorresi requested changes

2020-09-02 15:34 UTC, stefanotorresi commented on salt/cluster_node/ha/iscsi_initiator.sls
> +{% if grains['osrelease_info'][0] >= 15 and (grains['osrelease_info']|length > 1 and grains['osrelease_info'][1] >= 2) %}
Sorry xabi, I hate to bother you further with this :grimacing: but the whole condition now skips SLE16 specifically, because the second segment of the version is always compared to 1.

The final version should be:
```suggestion
{% if grains['osrelease_info'][0] > 15 or (grains['osrelease_info'][0] == 15 and grains['osrelease_info']|length > 1 and grains['osrelease_info'][1] >= 2) %}
```

2020-09-02 17:06 UTC, stefanotorresi approved these changes
we made it! :smile:

2020-09-02 17:33 UTC, merged