Add new documentation about SAP sofware usage
SUSE/ha-sap-terraform-deployments pull request #560
Opened 2020-10-08 13:00 UTC by arbulu89

New documentation about how to setup the SAP software required for the installation.

Please, have a deep look, and try to understand how we configure our files, to see if there is something wrong or missing.
If we don't check if what says is good, it's just more bunch of text that might not help.
Do the exercise with our buckets to understand how they are structured.

2020-10-10 05:37 UTC, Simranpal requested changes
@arbulu89  Thank you for this effort in documentation. I have made some suggestions/improvements below

2020-10-10 05:37 UTC, Simranpal commented on doc/sap_software.md
> +2. HANA database in `.SAR` format. This option consist on a unique `.SAR` file. To use this options, the `SAPCAR` utility is mandatory, so it must be downloaded from the same download center.
`HANA database in .SAR format. This archive format consist of only the HANA Database Server component. It will contain a particular Patchlevel or revision of only the database component of HANA platform. To extract this options, the SAP SAPCAR utility is mandatory, which must be downloaded from the SAP download center.`

2020-10-10 05:37 UTC, Simranpal commented on doc/sap_software.md
> +The configuration of the installed software for Netweaver or S4HANA depends on the used `SWPM` version. To install `NW750` and `S4HANA 1709` versions, `SWPM` version 1 is needed. Beyond `S4HANA 1809`
SAP Netweaver or S/4HANA are installed using the SAP Software Provisioning Manager (`SWPM`). The SWPM tool has different versions (1.0 and 2.0 major versions) and each version of this tool supports installation of only compatible Netweaver or S/4 HANA versions. Note: It is important to check and use the right versions to avoid issues during SAP installation. To install `NW750` and `S4HANA 1709` versions, `SWPM` version 11.0 is needed. Beyond `S4HANA 1809` `SWPM` version 2.0 is needed.

2020-10-10 05:37 UTC, Simranpal commented on doc/sap_software.md
> +### SWPM version 1
`1/1.0`

2020-10-10 05:37 UTC, Simranpal commented on doc/sap_software.md
> +1. `SWPM` archive. This usually comes compressed as a `.SAR` file, so the `SAPCAR` utility is required too. It will contain a `LABEL.ASC` such as `IND:SLTOOLSET:1.0:SWPM:*:LINUX_X86_64:*`.
`This usually comes compressed as a `.SAR` file and required the SAP `SAPCAR` utility to get extracted.`

2020-10-10 05:37 UTC, Simranpal commented on doc/sap_software.md
> +3. HANA client. This can be either the HANA platform used in the HANA installatio or the HANA client. The HANA client comes usually as `IMDB_CLIENT.SAR`.
`installatio/installation`

2020-10-10 05:37 UTC, Simranpal commented on doc/sap_software.md
> +2. Netweaver export files. Usually, it consists on a group of `.exe` and `.rar` files. The extracted folder has a `LABEL.ASC` such as `SAP:S4HANA:1709:DVD_EXPORT:S4HANA OP 102 Installation Export DVD
on/of

2020-10-10 05:37 UTC, Simranpal commented on doc/sap_software.md
> +4. The download basket must be complemented with the next archives. All of this components must be uploaded in the same folder.
`SAP exe folder. This is the download basket or the folder which must contain the following archives....`

2020-10-10 05:37 UTC, Simranpal commented on doc/sap_software.md
> +This would be an example on how to configure the `terraform.tfvas` file for this option (the paths are relative paths from the used storage name).
`Below would be an example on how to configure the `terraform.tfvas` file based on above SAP components (the paths are relative paths from the used storage name).`

2020-10-10 05:37 UTC, Simranpal commented on doc/sap_software.md
> +### SWPM version 2
`2/ 2.0`

2020-10-10 05:37 UTC, Simranpal commented on doc/sap_software.md
> +### SWPM version 2
Also same comments as swpm version 1 section, for all the below points

2020-10-10 05:37 UTC, Simranpal commented on doc/sap_software.md
> +After downloading the described options, the files must be stored in the corresponding storage. Create a folder with a meaningful name (`sap_download_basket` for example), and upload there all the fi
.....`Otherwise, the project will download all the files, which are quite large in size`

2020-10-10 05:37 UTC, Simranpal commented on doc/sap_software.md
> +- The project doesn't check if the used SAP binaries are compatible between them (HANA database version with S/4HANA version, for example)
` The project doesn't check for compatibilities between the SAP software and tools (HANA database version with S/4HANA version, for example)`

2020-10-10 05:37 UTC, Simranpal commented on doc/sap_software.md
> +- The project doesn't check if the files are properly upload or structured. If they are not, the project will be executed and it will fail, sometimes being really difficult to find the root source.
`source/cause`

2020-10-10 05:37 UTC, Simranpal commented on libvirt/terraform.tfvars.example
> +# It will create the NFS export in /mnt_permanent/sapdata/{netweaver_sid} to be connected as {drbd_cluster_vip}:/{netwaever_sid} (e.g.: )192.168.1.20:/HA1
DRBD will create the NFS export....

2020-10-10 05:37 UTC, Simranpal commented on libvirt/terraform.tfvars.example
> +# It will create the NFS export in /mnt_permanent/sapdata/{netweaver_sid} to be connected as {drbd_cluster_vip}:/{netwaever_sid} (e.g.: )192.168.1.20:/HA1
{drbd_cluster_vip}:/`{netwaever_sid} / {netweaver_sid} `

2020-10-13 07:06 UTC, arbulu89 commented on doc/sap_software.md
> +4. The download basket must be complemented with the next archives. All of this components must be uploaded in the same folder.
I have doubts here. More documentation I read, I think the `SAP exe` folder is something we made up, because our NFS share folders had this name. The parameter in the configuration file its named `download_basket`

2020-10-13 07:08 UTC, arbulu89 commented
> @arbulu89 Thank you for this effort in documentation. I have made some suggestions/improvements below

Thanks @Simranpal . Really detailed review. I will take care of the suggestions

2020-10-13 08:56 UTC, arbulu89 commented on aws/terraform.tfvars.example
> +# Options for SWPM version 1:
I will just use `SWPM` instead the long name.

2020-10-13 09:06 UTC, arbulu89 commented on aws/terraform.tfvars.example
> +# AWS S3 bucket where all the Netweaver software is available. The next paths are relative to this folder.
As far as I see, all the descriptions of the providers, are quite aligned. If we add this `S3 bucket`, we will need to update the other providers too.

2020-10-13 09:42 UTC, arbulu89 commented
@Simranpal Changes done! Excellent review.

2020-10-13 14:06 UTC, Simranpal approved these changes
Thanks @arbulu89 looks good now

2020-10-14 06:45 UTC, arbulu89 commented
@diegoakechi @MalloZup @stefanotorresi Could you have a look? It's important that the documentation is reviewed for more people than just 1 :)

2020-10-14 10:31 UTC, stefanotorresi requested changes
LGTM other than some minor grammar typos.

2020-10-14 12:45 UTC, arbulu89 commented on doc/sap_software.md
> +In order to avoid these issues, running a manual installation the first time with the selected binaries is recommended.
Ok, I will remove this sentence. But in many cases, I have found that the automatic deployment was failing after trying a manual installation and finding out that the binaries are imcompatible (the GUI installation wizards shows the errors in a nicre way than the batch option)

2020-10-14 13:21 UTC, stefanotorresi approved these changes

2020-10-14 15:03 UTC, MalloZup commented on doc/sap_software.md
> +## Disclaimer
I would put the disclaimer on the top of the file.

Since for me this is why this documentation exists.

2020-10-14 15:05 UTC, MalloZup commented on doc/sap_software.md
> +Here are the things that the project **doesn't do** for you:
I would maybe rename the `disclaimer` to `prerequisites` or like `requirements` or before installation section.

2020-10-14 15:11 UTC, MalloZup requested changes
I think we can improve the `Disclaimer` section.

As I read it, it feels like we need to justify something.

I think is full ok to expect the user to have kind of `requirements` sections before "running" the installation.

SO imho that should renamed and put on the top.

I would also invert the logic of the sentence. Instead of saying what we don't do, I would concentrate on what the user need to do .

E.g:

# Requirement:

Before executing the automatic-installation you need to fullfill following 
- You need to downlad and structure the SAP installation software.
- Check the compatibility between the SAP software and tools (HANA database version with S/4HANA version, for example)
- Before  executing the automatic install, check if the files are properly uploaded and  structured.

2020-10-15 06:29 UTC, arbulu89 commented on doc/sap_software.md
> +## Disclaimer
I don't agree. The documentation exists to explain the user what SAP software is needed for the deployment. The disclaimer is just that, a disclaimer saying what they shouldn't expect. This is what `disclaimer` chapters are for, some text to warm that if things to the users.

2020-10-15 06:31 UTC, arbulu89 commented on doc/sap_software.md
> +Here are the things that the project **doesn't do** for you:
I don't see them as prerequisites or requirements. They are things that the project doesn't do, and the user must be aware of.

2020-10-15 06:34 UTC, arbulu89 commented
> looks good +1
> Only 1 thing
> 
> I think we can improve the `Disclaimer` section.
> 
> As I read it, it feels like we need to justify something.
> 
> I think is full ok to expect the user to have kind of `requirements` sections before "running" the installation.
> 
> SO imho that should renamed and put on the top.
> 
> I would also invert the logic of the sentence. Instead of saying what we don't do, I would concentrate on what the user need to do .
> 
> E.g: (something i this direction)
> # Requirement:
> 
> Before executing the automatic-installation you need to fullfill following
> 
>     * You need to downlad and structure the SAP installation software.
> 
>     * Check the compatibility between the SAP software and tools (HANA database version with S/4HANA version, for example)
> 
>     * Before  executing the automatic install, check if the files are properly uploaded and  structured.
> 
> 
> Not respecting the requirement will cause the install to unexpected failures.

Honestly, I wouldn't change this. We are not justifying things in my opinion, the document just clarifies the things the project doesn't do in order to avoid missconceptions.
I would say that the document tells quite clearly, that this things must be done before the execution. That's the whole content of the document.

@stefanotorresi @Simranpal What do you think about the disclaimer entry? I like how it is now.

2020-10-15 07:29 UTC, MalloZup commented
@arbulu89  I personally never saw upstream documentation with a disclaimer a the end what the user shouldn't do.

Instead I see documentation of requirements and what user should at begin.

But If others are ok with this I can approve. 

A part of that good work!

2020-10-15 07:42 UTC, arbulu89 commented
@MalloZup The disclaimer is not saying what the user should do. It says what not to expect from the project. Things that maybe the user think the project does.

The documentation is already saying which are the things the user must do at the beginning, actually the document only says that, how to prepare your storage to use the project.

2020-10-15 07:46 UTC, MalloZup commented
@arbulu89  fair enough . I never saw it. Anyways. I will approve if @stefanotorresi @Simranpal  are ok with me or you we can change.

I think is an impression I got but is not something I will fight for :grin:

2020-10-15 07:47 UTC, MalloZup approved these changes
I'm approving but @stefanotorresi @Simranpal  if you think we should go without disclaimer then say it otherwise we can merge

2020-10-15 10:14 UTC, stefanotorresi commented on doc/sap_software.md
> +## Disclaimer
I agree with Dario, actually: disclaimers are usually put first, so that users are better aware of the assumptions that the rest of the document makes. Putting the assumptions at the end is quite counter-intuitive.

2020-10-15 10:16 UTC, stefanotorresi commented
I kinda like what Dario is suggesting: reversing the semantic of the disclaimer so that, instead of framing those things as "things we won't do for you", we frame them as "things you really ought to take care of by yourself", thus making these requirements, would make the assumptions made in the rest of the document more clear.

2020-10-15 11:31 UTC, arbulu89 commented
@MalloZup @stefanotorresi As it looks that there is majority on this topic, I have updated the `Disclaimer` chapter by `Requirements`. Have a look please

2020-10-15 12:00 UTC, stefanotorresi commented
:top: !

2020-10-15 12:00 UTC, MalloZup approved these changes
looks good thx !

2020-10-16 06:30 UTC, merged