Add option to use deployment_name instead of workspace string
SUSE/ha-sap-terraform-deployments pull request #566
Opened 2020-10-19 09:41 UTC by arbulu89

Implement the option to create the infrastructure names based on a new variable named `deployment_name`. This variable has preference over the terraform workspace, but if it's not used, the terraform workspace is used, as it is in the current code. So, there is not any non backward compatible change

2020-10-19 10:01 UTC, MalloZup reviewed
I/m ok with this.

I would however rename it to more strong from `deployment_name`  to `deployment_unique_name` or `deployment_uid` to make clear that the name is a UID if the user changes it, or do with 2 same there are problems.

2020-10-19 10:03 UTC, MalloZup requested changes
I'm ok with this! 

 but I would rename the variable with `deployment_unique_name` or `deployment_UID` or something more strong the `deployment_name`

2020-10-19 11:44 UTC, arbulu89 commented
I don't know if changing names would clarify that much. Maybe adding this information in the `description` of the variable and the examples file would be enough.

The variable is used to give a name to the deployment, the fact that it must be unique is more a feature/limitation than a description.

2020-10-19 12:23 UTC, MalloZup approved these changes
I'm personally like the `unique` but I'm ok if we add description

2020-10-19 15:06 UTC, Simranpal commented on aws/variables.tf
> +  description = "Name used to complement some of the infrastructure resources name as sufix. If it is not provided, the terraform workspace string is used"
Ok i see you correct the typo

2020-10-20 06:39 UTC, arbulu89 commented on aws/variables.tf
> +  description = "Name used to complement some of the infrastructure resources name as sufix. If it is not provided, the terraform workspace string is used"
Thanks @Simranpal 
Updated to: `Suffix string added to some of the infrastructure resources names. If it is not provided, the terraform workspace string is used as suffix`

As not all of the infrastructure resources have the suffix

2020-10-20 06:43 UTC, merged