Sap blue horizon text changes
SUSE/ha-sap-terraform-deployments pull request #577
Opened 2020-10-26 10:49 UTC by petersatsuse

Text changes to provide more context
adaption of the instance size to new types
fix large instance size as it had complete wrong settings

2020-10-26 15:46 UTC, arbulu89 requested changes
@petersatsuse I like the new text. Good job!
I suggested some changes in the variables page.

2020-10-26 15:46 UTC, arbulu89 commented on blue_horizon/azure/locales/custom-en.yml
> +    Doing SAP sizing right is not easy, therefor a simplified sizing approach is used.
Typo `therefor/therefore`

2020-10-26 15:46 UTC, arbulu89 commented on blue_horizon/azure/locales/custom-en.yml
> +       See Microsoft documentation [Howto create a storage account][]
`[Howto create a storage account][]` looks like duplicated

2020-10-26 15:46 UTC, arbulu89 commented on blue_horizon/azure/locales/custom-en.yml
> +       [Howto create a storage account]:https://docs.microsoft.com/en-us/azure/storage/files/storage-how-to-create-file-share?tabs=azure-portal#create-a-storage-account
To create a link follow should be [Howto create a storage account](https://docs.microsoft.com/en-us/azure/storage/files/storage-how-to-create-file-share?tabs=azure-portal#create-a-storage-account)

2020-10-26 15:46 UTC, arbulu89 commented on blue_horizon/azure/locales/en.yml
> +    cluster: "Sizes"
This change should go in `custom-en.yml` rather than `en.yml`. Just add in `en`:
```
sidebarL
  cluster: "Sizes"
```

2020-10-26 15:46 UTC, arbulu89 commented on blue_horizon/azure/locales/en.yml
> +    deploy: "Deploy your machines"
The same. It should go in `custom-en.yml`

2020-10-26 15:46 UTC, arbulu89 commented on blue_horizon/azure/sources/variables.tf.json
> +    "ssh_authorized_keys": {
I don't know if this should be a list or an individual box. If we finally merge the option to upload files, we won't be able to use lists.

2020-10-26 15:46 UTC, arbulu89 commented on blue_horizon/azure/sources/variables.tf.json
> +    "ssh_authorized_keys": {
Actually, i see later `ssh_authorized_key`, so this one might not be needed

2020-10-26 15:46 UTC, arbulu89 commented on blue_horizon/azure/sources/variables.tf.json
> +      "description": "HANA SID. The System identifier (SID) must be 3 letters"
The SID accepts numbers to (not as first character). We will work on the limitations in the short future applying regular expressions

2020-10-26 15:46 UTC, arbulu89 commented on blue_horizon/azure/sources/variables.tf.json
>      "system_identifier": {
I think we would need to add the HANA entries in a group to (`HANA configuration` maybe). Otherwise they will be grouped as `Additional data`

2020-10-26 15:46 UTC, arbulu89 commented on blue_horizon/azure/sources/variables.tf.json
> +    "storage_account_name": {
This last 2 entries look duplicated, right? 
They are set in the `Azure configuration`

2020-10-26 15:52 UTC, petersatsuse commented on blue_horizon/azure/locales/custom-en.yml
> +       See Microsoft documentation [Howto create a storage account][]
no this is the text for the link - markdown syntax to show a text instead of a link

2020-10-26 15:56 UTC, petersatsuse commented on blue_horizon/azure/locales/custom-en.yml
> +       See Microsoft documentation [Howto create a storage account][]
yes

2020-10-26 15:58 UTC, petersatsuse commented on blue_horizon/azure/sources/variables.tf.json
> +    "ssh_authorized_keys": {
i was also wondering about that double entry. i only changed the group, and i think the some more variables should go to groups

2020-10-26 15:59 UTC, petersatsuse commented on blue_horizon/azure/sources/variables.tf.json
> +      "description": "HANA SID. The System identifier (SID) must be 3 letters"
There is a whole regex needed, as SAP also has some values not allowed. We have it in the yast install wizard ... i need to search for it.

2020-10-26 15:59 UTC, petersatsuse commented on blue_horizon/azure/sources/variables.tf.json
>      "system_identifier": {
yes - think so too

2020-10-26 16:03 UTC, petersatsuse commented on blue_horizon/azure/sources/variables.tf.json
> +    "storage_account_name": {
hmm did not add them - but yes you are right

2020-10-26 16:15 UTC, arbulu89 commented on blue_horizon/azure/sources/variables.tf.json
> +      "description": "HANA SID. The System identifier (SID) must be 3 letters"
This is the expression: `/^(?!ADD|ALL|AND|ANY|ASC|COM|DBA|END|EPS|FOR|GID|IBM|INT|KEY|LOG|MON|NIX|NOT|OFF|OMS|RAW|ROW|SAP|SET|SGA|SHG|SID|SQL|SYS|TMP|UID|USR|VAR)[A-Z][A-Z0-9]{2}$`.
Anyway, this will come hidden somehow in the new feature to add client side validation

2020-10-26 23:40 UTC, MalloZup commented
can we have a screenshot to visualize this? Tia :sunflower:

2020-10-27 09:59 UTC, arbulu89 requested changes
@petersatsuse I still see some needed improvements.
1. The `[Howto create a storage account]` link is still not created properly
2. `deployment_type` should go in `hana_configuration` group, or some other group. Having it in `Additional data` looks strage. 
3. The `ssh_authorized_keys` value and description is invalid. We say `keys paths`, but we cannot use this way. For that we should upload the file. Right now, the options is to paste the content of the public key there.

2020-10-27 09:59 UTC, arbulu89 commented on blue_horizon/azure/locales/custom-en.yml
> +       [Howto create a storage account]:https://docs.microsoft.com/en-us/azure/storage/files/storage-how-to-create-file-share?tabs=azure-portal#create-a-storage-account
This is still wrong. The `[text]:link` doesn't work. It must be `[text](link)`. Otherwise nothing is visualized

2020-10-27 13:06 UTC, arbulu89 approved these changes
Thanks @petersatsuse 
Nice work

2020-10-27 13:24 UTC, merged