Feature/add common variables
SUSE/ha-sap-terraform-deployments pull request #580
Opened 2020-10-27 01:11 UTC by Simranpal

We have added a lot of new variables, that  are mainly used to render the salt pillar files. With this PR, we move most of the HANA/Netweaver variables from all the modules of all providers in the "common_variables" module. 
With this we will get:

- `common_variables` module contain most of the hana/nw variables for all providers and one place to configure
- The grains will be the same for this topic, avoiding issues like ("I have forgotten to add this variable to this cloud provider")
- We reduce the duplicated code in the `salt_provisioner.tf` files
- We wouldn't have any change for the user

So far I am adding the variables that are used to render the pillar files. Some of the variables are used both in terraform and pillar/grains, so I have not added them as their usage varies by providers in terraform.

- hana_cluster_vip
- hana_cluster_vip_secondary
- ha_enabled
etc

and some variables I have not added to `common_variables` because they are not used in the pillar like `hana_disk_device`.
I am currently doing the changes for netweaver modules.

2020-10-27 07:27 UTC, MalloZup reviewed
I'm not sure if this logically is correct.

e.g `common_variables` are imho `host` releated variables.

If we add `hana/nw` the category becomes more ambigous

2020-10-27 07:40 UTC, arbulu89 reviewed
@Simranpal It looks good. There are still variables that I would set in the `common_variables` though.
Remember, common variables are the variables that are used in all cloud providers.
Just, maybe some of them cannot be added there, because we would create cyclic imports (like in the bastion PR). So they must be excluded by force

2020-10-27 07:40 UTC, arbulu89 commented on aws/main.tf
> +  hana_inst_master           = var.hana_inst_master
I still see some variable that I think should go to common_variables.
Remember, common variables are the variables that are used in all cloud providers.
- `hana_inst_master`
- `hana_cluster_vip`
- `hana_cluster_vip_secondary`
- `fencing_mechanism` (that in the common variables would be `hana_cluster_fencing_mechanism`
- `sbd_storage_type`
- `iscsi_srv_ip`
- `cluster_ssh_pub`
- `cluster_ssh_key`
`hwcct` should be removed as it is already in `common_variables`

2020-10-27 07:42 UTC, arbulu89 commented on generic_modules/common_variables/hana_variables.tf
> +  default     = "/sapmedia/HANA"
This should be `/sapmedia_extract/HANA`.
In any case, we should consider removing all the `default` as they are already set in the main `variables.tf` files.

2020-10-27 08:42 UTC, MalloZup reviewed
we should rename `common_variable` to `common_cloud_variables` or `sap_common_variables`. or related

Right now the `common_variable` is empty like `utils`, it is a bad naming

2020-10-28 04:16 UTC, Simranpal commented on aws/main.tf
> +  hana_inst_master           = var.hana_inst_master
@arbulu89 regarding this variables:

- `hana_inst_master` I added now, replacing `hana_inst_media` in libvirt with `hana_inst_master` so its common on all providers
- `hana_cluster_vip` this variable is set differently inside Azure grains, so we cannot have it same for all providers
- `hana_cluster_vip_secondary` is used in the terraform hana module code, so if we want to use it in `common_variables` module, it also need to assigned in module "`hana_node`" in main.tf.  I am not sure if this will cause confusion with 2 assignments in main.tf.
- `sbd_storage_type` is used in the terraform hana module code for libvirt, again same issue as 2 assignments in main.tf. One in common variable and other in hana module. Besides that it used in multiple modules like hana, nw, drbd with the same value. And other grains entry depend on it like `sbd_disk_device`. So defining in two places causes confusion which one is being used.
- `ha_enabled` same issue as 2 assignments
- `cluster_ssh_pub`, `cluster_ssh_key` are not available in libvirt
- `iscsi_srv_ip` and `hwcct` was not in common_variables but I added now

2020-10-28 04:31 UTC, Simranpal commented on aws/main.tf
> +  hana_inst_master           = var.hana_inst_master
`iscsi_srv_ip` in common variables caused cycle issue, so I reverted back

2020-10-28 04:33 UTC, Simranpal commented on aws/main.tf
> +  hana_inst_master           = var.hana_inst_master
Similarly `hana_inst_master` did not exist for GCP, so I will revert to existing usage

2020-10-28 04:35 UTC, Simranpal commented
> we should rename `common_variable` to `common_cloud_variables` or `sap_common_variables`. or related
> 
> Right now the `common_variable` is empty like `utils`, it is a bad naming

I am not sure about a good naming here. As it will contain variables common to all providers and various modules, the name of module itself `common_variables` is reasonable to me.

2020-10-28 07:18 UTC, arbulu89 commented
> > we should rename `common_variable` to `common_cloud_variables` or `sap_common_variables`. or related
> > Right now the `common_variable` is empty like `utils`, it is a bad naming
> 
> I am not sure about a good naming here. As it will contain variables common to all providers and various modules, the name of module itself `common_variables` is reasonable to me.

I like `common_variables` too. Adding cloud is redundant in my opinion, the project is already based on cloud platforms, why would we like to add it again here?

2020-10-28 07:26 UTC, arbulu89 reviewed
@Simranpal I still think that we can add more variables to the `common_variables`, like
- `hana_cluster_vip`
- `hana_cluster_vip_secondary`
- `ha_enabled`
- `fencing_mechanism`
- `sbd_storage_type`

We can use these variables in the modules again, as we do with the current common_variables.
At the end, the goal is to unify the variables among the providers to avoid duplicated code and issues maintaining this.

2020-10-28 07:26 UTC, arbulu89 commented on aws/main.tf
> +  hwcct                               = var.hwcct
I would put `hwcct` just after `qa_mode`, to have things in order

2020-10-28 07:26 UTC, arbulu89 commented on generic_modules/common_variables/outputs.tf
> +EOF
Here, besides adding the data to the grains, I would add all the variables as we do with the other. Maybe, we could create a map where using `hana` as key we can include all the elements there so they might be used later. I mean something like:

```
output "configuration" {
  value = {
    provider_type = var.provider_type
    ...
    hana = {
      sid = var.hana_sid
      instance_number = var.hana_instance_number
    }
    grains_output = <<EOF
...
```

This way everything is available to be used even by terraform

2020-10-30 11:13 UTC, arbulu89 requested changes
@Simranpal In general looks fine, but I have added some additional comments.

2020-10-30 11:13 UTC, arbulu89 commented on generic_modules/common_variables/outputs.tf
> +      sid = var.hana_sid
This format doesn't look like follows HCL format rules. The `=` character should start in the same place in all lines to improve readability

2020-10-30 11:13 UTC, arbulu89 commented on generic_modules/common_variables/outputs.tf
> +    netweaver = {
I would put this before all grains, so all grains are set in sequence

2020-10-30 11:13 UTC, arbulu89 commented on generic_modules/common_variables/outputs.tf
> +hwcct: ${var.hwcct}
`hwcct` should go in `hana` grains, as this tool is just a tool to test HANA performance

2020-10-30 11:13 UTC, arbulu89 commented on generic_modules/common_variables/variables.tf
> +variable "hwcct" {
This should go in `hana_variables.tf` file

2020-10-30 11:13 UTC, arbulu89 commented on libvirt/main.tf
> +  ascs_instance_number                = var.netweaver_ascs_instance_number
Maybe, we should take advantage and add `netweaver` prefix to these variables

2020-10-30 11:13 UTC, arbulu89 commented on libvirt/main.tf
> +  scenario_type                       = var.scenario_type
I would add `hana` prefix to the variable, only to the one in the module, so we have a better understanding

2020-10-30 11:13 UTC, arbulu89 commented on aws/main.tf
> +  hana_cluster_vip           = local.hana_cluster_vip
I don't still understand why don't you put `hana_cluster_vip` in the common variables. Is there any reason?
You know that you can get this data in the module like `var.common_variables["hana"]["cluster_vip"]`, right?

2020-10-30 15:15 UTC, Simranpal commented on aws/main.tf
> +  hana_cluster_vip           = local.hana_cluster_vip
I already added in common variables. `hana_cluster_vip` is still used in the hana module terraform code. So I had to pass it to module. 
Eg: https://github.com/SUSE/ha-sap-terraform-deployments/blob/86d8ec8671a680596323c89bbd5b6c407daf2560/aws/modules/hana_node/main.tf#L30

2020-10-30 15:19 UTC, Simranpal commented on generic_modules/common_variables/outputs.tf
> +      sid = var.hana_sid
The terraform `fmt` did not format it. But I can do it manually

2020-11-02 09:14 UTC, arbulu89 commented on aws/main.tf
> +  hana_cluster_vip           = local.hana_cluster_vip
That's not a limitation. You don't need to pass to the module if it is in the common variables.
Please, read my last comment.
You can use `var.common_variables['hana']['cluster_vip']`.
Everything you pass to the common variables is available in module, so you don't need to pass again.

2020-11-03 01:01 UTC, Simranpal commented on aws/main.tf
> +  hana_cluster_vip           = local.hana_cluster_vip
Yes I understand, I was also thinking to keep the variable name short in the terraform code. But it makes sense to use the values from common variables, as is being used elsewhere too

2020-11-03 07:24 UTC, arbulu89 approved these changes
@Simranpal Good job!
It looks great!
Please, could you add in the PR main description the changed variables names (`hana_inst_master` for example). Just in the PR description to have it at hand in the future

2020-11-03 07:24 UTC, arbulu89 commented on aws/main.tf
> +  ha_enabled            = var.hana_ha_enabled
`ha_enabled` is already in the common variables, right?

2020-11-03 07:24 UTC, arbulu89 commented on aws/main.tf
> +  ha_enabled            = var.netweaver_ha_enabled
`ha_enabled` is already in the common variables, right?

2020-11-03 18:42 UTC, Simranpal commented on aws/main.tf
> +  ha_enabled            = var.hana_ha_enabled
yes I have removed it from the modules now

2020-11-04 03:09 UTC, Simranpal commented
@arbulu89 thanks, i have updated the description and done some changes to fix minor issues. I have now tested successfully with deployment in `libvirt` and `azure`

2020-11-04 07:35 UTC, arbulu89 commented
@Simranpal It looks good! Merge when you finish testing everything

2020-11-04 07:38 UTC, arbulu89 commented on generic_modules/common_variables/outputs.tf
> +      netweaver_sid             = var.netweaver_sid
I think we could remove `netweaver` prefix from this variables

2020-11-05 00:10 UTC, Simranpal commented on generic_modules/common_variables/outputs.tf
> +      netweaver_sid             = var.netweaver_sid
yes, I have removed from it all the ones with prefix inside this map

2020-11-05 00:59 UTC, merged