Add provisioning_output_colored variable
SUSE/ha-sap-terraform-deployments pull request #593
Opened 2020-11-11 09:38 UTC by arbulu89

Implementation of a non colored provisioning output. 
It adds the `provisioning_output_colored` variable to decide whether the provisioning scripts output is colored or not.

Until now, this was done using the `qa_mode` option.

This feature is a good go have thing if the project is used in environments such as blue-horizon.
To use ansii output colors in html is not trivial, as you need to translate all the characters by html tags and span entries, and besides that, salt/terraform combo doesn't just put colors in individual lines, so it makes things really difficult. I think going colorless is the best by now.

**INFO: Unfortunately the `SUSEConnect` tool doesn't have the option to disable colors, so this command output always be colored...*

2020-11-12 13:24 UTC, stefanotorresi requested changes
LGTM other than a couple of minor changes to the shell script!

2020-11-12 13:24 UTC, stefanotorresi commented on salt/provision.sh
> +provisioning_output_colored () {
I guess this is not just the colored one, it's `provisioning_output` in general.

2020-11-12 13:24 UTC, stefanotorresi commented on salt/provision.sh
> +    if [[ "$(get_grain provisioning_output_colored)" == "true" ]]; then
maybe we should consider extracting `$(get_grain provisioning_output_colored)` in a global variable instead of calling it repeatedly inside many functions.

2020-11-12 13:46 UTC, MalloZup approved these changes
ok to me thx!

2020-11-13 14:26 UTC, arbulu89 commented on salt/provision.sh
> +provisioning_output_colored () {
I don't get this.
This function is used to return the salt options about coloring, `--force-color` or `--no-color`. Why do you think that it's not about colored?
Maybe it could be renamed to `salt_output_colored` or `salt_color_flag` as it's exclusive for salt

2020-11-13 14:59 UTC, arbulu89 commented on salt/provision.sh
> +    if [[ "$(get_grain provisioning_output_colored)" == "true" ]]; then
Having global variables is not that simple here. Have in mind that this script is based in different flags and execution. This means that we don't always execute the same code.
For example, we execute it 2 times, during the regular deployment. First to initialize, and after the reboot to finish the configuration.
During this process, the `grains` file is moved from `/tmp/grains` to `/etc/salt/grains`.
This means that we cannot just initialize the variables at the beginning of the script.
To handle all this complexity, we would eventually need to control more things making the code more complex.
Do you think that it's worthy?

2020-11-13 15:25 UTC, stefanotorresi commented on salt/provision.sh
> +    if [[ "$(get_grain provisioning_output_colored)" == "true" ]]; then
uhm, no, absolutely not worth it, let's leave it repeated! :grimacing:

2020-11-13 15:28 UTC, stefanotorresi commented on salt/provision.sh
> +provisioning_output_colored () {
Ohh, that wasn't clear at all to me! I thought this function would actually print the output, colored or not.
Then yes, I would appreciate going with `salt_color_flag` to make this clearer.

2020-11-13 15:42 UTC, arbulu89 commented on salt/provision.sh
> +provisioning_output_colored () {
Updated to `salt_color_flag`.
Thanks for the review!

2020-11-13 15:43 UTC, stefanotorresi approved these changes
all good!

2020-11-13 17:15 UTC, merged