blue horizon tuning dashboard and exporter setup
SUSE/ha-sap-terraform-deployments pull request #598
Opened 2020-11-18 10:27 UTC by MalloZup

# Note for reviewers:

review commit by commit so you have less files

# Description:

This pull-request add:

- the new `tuning.json` dashboard which is the saptune_exporter dashboard
- an option for grafana.ini to allow dashboards/panels to be embedded (by default this is disabled by grafana)
- add the saptune_exporter systemd-service activation on hana nodes

2020-11-19 11:39 UTC, stefanotorresi requested changes
I'm not sure if we should pursue proper vendoring of the web console assets here.
Committing a bazillion files from the eos-design system when that's already packaged with a node module feels like quite a liability.

@arbulu89 what do you think here? Do we want to go quick and dirty or do we go slow and smooth?

2020-11-19 11:39 UTC, stefanotorresi commented on salt/hana_node/saptune_exporter.sls
> +prometheus_ha_cluster_exporter:
copy-paste leftover? ;)

2020-11-19 11:51 UTC, stefanotorresi commented
> Committing a bazillion files from the eos-design system when that's already packaged with a node module feels like quite a liability.

to clarify, a cleaner way to go about this would be to include just a package.json file instead of the EOS files, then, via Salt states, install nodejs and npm from an opensource repo, and run `npm install` from the website dir.

2020-11-19 13:16 UTC, arbulu89 requested changes
@MalloZup @stefanotorresi I agree with your approach. Better try to have a neat project installing the styles from a package (even if it's npm).
This way it is much easier to know our current html file.

Besides that, we need to open the new saptune exporter port in the security rules, and maybe the load balancer. Have a look no how the other exporters work

2020-11-19 13:16 UTC, arbulu89 commented on salt/monitoring_srv/grafana.sls
> +    - after: \[security\]
Is this `after` secure?
Shouldn't we find the current `allow_embedding` entry and replace it.
If there is not this value, I guess we can go with this option

2020-11-19 14:00 UTC, MalloZup commented on salt/monitoring_srv/grafana.sls
> +    - after: \[security\]
this follow the same pattern we used on already merged state. 

The value is already there but uncommented so is not existing there.

2020-11-19 14:05 UTC, MalloZup commented on salt/monitoring_srv/grafana.sls
> +    - after: \[security\]
https://github.com/SUSE/ha-sap-terraform-deployments/blob/develop/salt/monitoring_srv/grafana.sls#L12

2020-11-19 14:06 UTC, MalloZup commented on salt/hana_node/saptune_exporter.sls
> +prometheus_ha_cluster_exporter:
done thx

2020-11-20 07:41 UTC, arbulu89 requested changes
@MalloZup I think that this won't work yet for Azure. There are thing that are missing about the new exporter:
- Open security ports
- Forward ports in the load balancer (this might not be needed, as the exporter is installed in all nodes, but have a look anyway).
Have a look in how the other exporters work
Please, work based in Azure

2020-11-20 07:41 UTC, arbulu89 commented on salt/hana_node/saptune_exporter.sls
> +    - restart: True
@MalloZup I think this `restart` option doesn't exist. Let's remove it.
If you need a restart, there are other alternatives I think

2020-11-20 09:32 UTC, MalloZup commented on salt/hana_node/saptune_exporter.sls
> +    - restart: True
done

2020-11-20 09:36 UTC, arbulu89 approved these changes
Thanks @MalloZup

2020-11-20 10:11 UTC, MalloZup commented
@stefanotorresi  are you ok with this or do you wants more changes? let me know tia

2020-11-20 10:49 UTC, MalloZup commented
follow-up: https://github.com/SUSE/ha-sap-terraform-deployments/issues/601

2020-11-20 11:05 UTC, merged