Fix network restart on SLE15-SP3
SUSE/ha-sap-terraform-deployments pull request #600
Opened 2020-11-19 10:30 UTC by ldevulder

Current code tries to enable the network service which lead to an error on SLE15-SP3 because service is already enabled.
In fact, it's not really needed to enable this service, so better to remove this `Enable:` option.

This PR also force-adds the `CLOUD_NETCONFIG_MANAGE` option, to ensure that there will be no issues if `cloud-init` is used.

Tested on 15-SP2 and 15-SP3 images.

2020-11-19 10:36 UTC, ldevulder commented
During my investigations and tests I found that some sls files have `restart: True` set in `service.running`, but this option doesn't exist (see https://docs.saltstack.com/en/latest/ref/states/all/salt.states.service.html#starting-or-restarting-of-services-and-daemons), and I checked the salt code to be sure.

In fact, as long as the syntax is correct you can add whatever you want, I tested by setting `bidule: True` and it "works" (it does nothing but no error).

So I think that `restart: True` could be removed from these files:
- `/salt/cluster_node/monitoring.sls`
- `/salt/monitoring_srv/grafana.sls`
- `/salt/monitoring_srv/loki.sls'

WDYT? I could do it in this PR or in another.

2020-11-19 11:17 UTC, MalloZup commented on salt/cluster_node/ha/network.sls
> +    - append_if_not_found: True
I would add a comment  here why this option exists. namely what you wrote 
`
 ensure that there will be no issues if cloud-init is used.`

2020-11-19 11:18 UTC, MalloZup reviewed
looks good only I would add the comment why we add the `append_if not_found`

2020-11-19 11:39 UTC, MalloZup commented
@ldevulder  good catch about the restart true, :+1: sofar I could also not find evidence why we need it.
I would not mind if you remove it here with a separete commits and just do 1 test to see if everything is ok !

2020-11-19 13:00 UTC, arbulu89 commented on salt/cluster_node/ha/network.sls
> +    - append_if_not_found: True
The is already a comment on top of the file. Have a look to the entire file

2020-11-19 13:02 UTC, arbulu89 commented
@ldevulder If this happens, it looks like a bug in salt core code. Why should it complain if it's enable and you want to enable? It should do nothing and that's it.
Could you paste the error code here?

2020-11-19 13:12 UTC, MalloZup commented on salt/cluster_node/ha/network.sls
> +    - append_if_not_found: True
ok

2020-11-19 15:58 UTC, ldevulder commented
> @ldevulder If this happens, it looks like a bug in salt core code. Why should it complain if it's enable and you want to enable? It should do nothing and that's it.
> Could you paste the error code here?

The error is not in salt but in systemd, it's because we try to enable a service (network) that is in fact a link to another service (wicked) and that's not allowed. Should be a change in systemd I think, but I checked and that's normal, not a bug in systemd.

Here the error I have: `Failed to enable unit: Refusing to operate on alias name or linked unit file: network.service`

> Besides that, we cannot include this append_if_not_found: True always. I guess that in libvirt it is not used. It should have a
> conditional to wrap it.
It could be added as it's used only by `cloud-init` and nothing else. I can remove it yes if you really want, but `cloud-init` could also be used in libvirt VM. The idea of force to have this line in the code is also to ensure that if `cloud-init` is activated later (don't know why but technically it could be) the HA cluster will not have the issue documented in the KB note.

2020-11-19 15:58 UTC, ldevulder commented on salt/cluster_node/ha/network.sls
> +    - append_if_not_found: True
Yes, I think that the KB note is enough.

2020-11-19 16:00 UTC, ldevulder commented
> @ldevulder good catch about the restart true,  sofar I could also not find evidence why we need it.

In any case if a restart is needed it will be done, as it's the default behavior of the `watch` command.

> I would not mind if you remove it here with a separete commits and just do 1 test to see if everything is ok !

Ok, will do it.

2020-11-20 07:50 UTC, arbulu89 requested changes

2020-11-20 07:50 UTC, arbulu89 commented on salt/cluster_node/ha/network.sls
> +    - append_if_not_found: True
@ldevulder I think we need to make this `append_if_not_found` conditional.
This value is only for the cloud providers, not for `libvirt` so I think we don't need to add it if it doesn' exist

2020-11-25 17:00 UTC, ldevulder commented on salt/cluster_node/ha/network.sls
> +    - append_if_not_found: True
Added, but as I explained previously `cloud-init` could be used in `libvirt` also, and added an unused variable in this file doesn't hurt.

2020-11-26 07:46 UTC, arbulu89 approved these changes
Thanks @ldevulder

2020-11-26 11:22 UTC, ldevulder commented
Last tests shown no issue on `master` branch.

2020-11-26 11:23 UTC, merged