Update issue templates
SUSE/ha-sap-terraform-deployments pull request #652
Opened 2021-03-09 08:50 UTC by arbulu89

Github issues template. Now that we are receiving more issues, we need to ask for specific information to make the analysis smoother

2021-03-09 09:40 UTC, stefanotorresi requested changes
Instead of "Describe the bug", I would suggest asking for a step-by-step description on how to reproduce it consistently, and also the expected result vs the observed behaviour.

2021-03-09 11:05 UTC, MalloZup commented on .github/ISSUE_TEMPLATE/bug_report.md
> +A clear and concise description of what the bug is.
we can add here on the line

`A clear and concise description of what the bug is and how to reproduce it`

2021-03-09 11:07 UTC, MalloZup approved these changes
looks good to me. Personally I like the sentence how to reproduce it, since it tells the user to specify a step by step, whereas maybe describe the bug could be more "theoretical".

But as far we state it even later on I"m ok.

2021-03-09 11:29 UTC, stefanotorresi commented
> 1. You modify the terraform.tvars
> 2. Run terraform commands

That's a big assumption! Users will do all sorts of strange things with software. 😀

2021-03-10 08:25 UTC, arbulu89 commented
@stefanotorresi @MalloZup Template with new questions updates

2021-03-10 12:07 UTC, stefanotorresi approved these changes
perfect, thank you!

2021-03-10 14:17 UTC, merged