Implement the load balancer scenario to manage the VIP address in GCP
SUSE/ha-sap-terraform-deployments pull request #659
Opened 2021-03-12 08:55 UTC by arbulu89

Implementation of the load balancer usage to manage the VIP address in GCP.

Based on: https://cloud.google.com/solutions/sap/docs/sap-hana-ha-config-sles#configure_the_failover_support
Now the load balancer usage is recommend over the routes usage by GCP.

It includes:
- Load balancer implementation module
- The module is used by the primary VIP address, and by the secondary in a Active/Active setup
- Improve the documentation about `hana_cluster_vip_secondary` as I have worked with the Active/Active setup (this is expanded to all the providers)
- Update the cluster pillar template. In GCP the network mask for any of the interfaces must be 32, otherwise the network setup is messed up and nothing works.

**How to use**
To use different VIP mechanisms we need to update the `hana_cluster_vip_mechanism` variable. The options are `load-balancer` and `route` by now, and it is only applied in GCP

Depends on: https://github.com/SUSE/saphanabootstrap-formula/pull/121
Implements: https://github.com/SUSE/ha-sap-terraform-deployments/issues/625
Fixes: https://github.com/SUSE/ha-sap-terraform-deployments/issues/655

FYI: @ab-mohamed

2021-03-17 04:15 UTC, Simranpal requested changes
@arbulu89 please see some comments below

2021-03-17 04:15 UTC, Simranpal commented on gcp/modules/load_balancer/main.tf
> +  source_ranges = ["35.191.0.0/16", "130.211.0.0/22"]
I think we can refer to the GCP firewall rules page: https://cloud.google.com/load-balancing/docs/health-checks#fw-rule

in case the IPs change

2021-03-17 04:15 UTC, Simranpal commented on gcp/modules/hana_node/main.tf
> +  tcp_health_check_port = tonumber("625${var.common_variables["hana"]["instance_number"]}")
Where can I check/find these port numbers

2021-03-17 04:15 UTC, Simranpal commented on gcp/modules/load_balancer/variables.tf
> +  description = "List of tags that the load balancer forwards the traffic"
We can add this network tag is used by the firewall rule for health checks.

2021-03-17 12:19 UTC, arbulu89 commented on gcp/main.tf
> +  hana_cluster_vip_secondary_lb = var.hana_cluster_vip_secondary != "" ? var.hana_cluster_vip_secondary : cidrhost(local.subnet_address_range, local.hana_ip_start + var.hana_count + 1)
This is checked afterwards. Let's keep it as it is (that is already quite complex)

2021-03-17 12:20 UTC, arbulu89 commented on gcp/modules/load_balancer/main.tf
> +# And: https://cloud.google.com/solutions/sap/docs/sap-ha-config-sles
Thanks! Some copy/paste error. Nice catch

2021-03-17 12:22 UTC, arbulu89 commented on gcp/modules/load_balancer/main.tf
> +  source_ranges = ["35.191.0.0/16", "130.211.0.0/22"]
This is already specified in the other 2 links. Do we need to emphasize more?

2021-03-17 12:23 UTC, arbulu89 commented on gcp/modules/hana_node/main.tf
> +  tcp_health_check_port = tonumber("625${var.common_variables["hana"]["instance_number"]}")
They are made up by me. `azure` uses those, so I have just used the same. Otherwise we would need to ask them to the user. Should we?

2021-03-17 15:51 UTC, arbulu89 commented on azure/terraform.tfvars.example
> +# IP address used to configure the hana cluster floating IP. It must go in the same subnet than the hana machines
@Simranpal What about `It must belong to the same subnet...`

2021-03-17 15:57 UTC, arbulu89 commented on gcp/modules/load_balancer/main.tf
> +  source_ranges = ["35.191.0.0/16", "130.211.0.0/22"]
I will add the link

2021-03-17 16:06 UTC, arbulu89 commented
@Simranpal Issues addressed. Could you have a 2nd review?

2021-03-17 16:25 UTC, Simranpal commented on azure/terraform.tfvars.example
> +# IP address used to configure the hana cluster floating IP. It must go in the same subnet than the hana machines
Yes that sounds better

2021-03-18 00:47 UTC, Simranpal commented on gcp/modules/hana_node/main.tf
> +  tcp_health_check_port = tonumber("625${var.common_variables["hana"]["instance_number"]}")
I think thats okay, we can skip asking the user. I could not check the reference so wanted to make sure.

2021-03-18 00:48 UTC, Simranpal commented on gcp/modules/load_balancer/main.tf
> +  source_ranges = ["35.191.0.0/16", "130.211.0.0/22"]
Thanks yes the link is for firewall rules

2021-03-18 00:49 UTC, Simranpal approved these changes
Thanks @arbulu89 looks fine now

2021-03-18 07:48 UTC, merged