Initial commit for powervs
SUSE/ha-sap-terraform-deployments pull request #661
Opened 2021-03-15 16:14 UTC by mfriesenegger

The goal of this draft is to deploy a single HANA on PowerVS instance (no HANA system replication or HA).

2021-03-16 08:53 UTC, arbulu89 reviewed
Hey @mfriesenegger ,
It looks pretty good so far. Not much to complain. 
Keep going!

2021-03-16 08:53 UTC, arbulu89 commented on powervs/infrastructure.tf
> +  required_version = ">= 0.12"
Change this by `0.13`. This is the version we ship and support

2021-03-30 16:47 UTC, mfriesenegger commented on powervs/infrastructure.tf
> +  required_version = ">= 0.12"
Done.

2021-03-30 16:58 UTC, mfriesenegger commented
Force-push 068c887 includes updates which provision a single PowerVS instance through the predeployment operation.

2021-04-08 15:30 UTC, mfriesenegger commented
Force-push 88e7251 includes updates which provision a single PowerVS instance successfully installing SAP HANA.  The deployment has been tested using the IBM Cloud PowerVS approved image named Linux-SUSE-SAP-12-4.  

Several additional changes have been made but not included in this PR.

- Added an if statement to workaround_payg_cleanup because paygo does not apply to powervs.
- Currently using NFS from another PowerVS instances for SAP media storage.
- Removed /var/run/reboot-needed test condition because it is not implemented in 12 SP4.
- Updating python in provision.sh because salt may fail on minion_configuration if an older python is installed on 12 SPx systems.

@arbulu89 should these changes be be included in this PR, ignored or fixed outside of this PR?

2021-04-28 19:04 UTC, mfriesenegger commented
Force-push 3e13164 includes updates not included in 88e7251 to provision a single PowerVS instance successfully installing SAP HANA.

2021-05-03 06:29 UTC, arbulu89 requested changes
Hi @mfriesenegger ,

As far as I see the PR needs a lot of work. I couldn't add all the comments.
Some important notes:
- I see that you do changes in the code that is used by the other providers. This is really risky as it changes the behaviour of the others, and we don't want this. You should only include the powervs part to run only when is applied
- The `terraform.workspace` should be only used to create the `deployment_name` variable.

I see 2 options. We work on this PR until fixing everything, or we just merge it to the `powervs` branch and you continue with the work. And we do the the final revision when you have the whole thing finished.

I don't know which want is the best honestly, but I'm sure that if we merged this to `master/develop` it would break many things

2021-05-03 06:29 UTC, arbulu89 commented on generic_modules/salt_provisioner/main.tf
> -    bastion_host        = var.bastion_host
We cannot remove this. It is used by the other providers

2021-05-03 06:29 UTC, arbulu89 commented on generic_modules/salt_provisioner/main.tf
> -      "${var.reboot} && [ -f /var/run/reboot-needed ] && echo \"Rebooting the machine...\" && (nohup sudo sh -c 'systemctl stop sshd;/sbin/reboot' &) && sleep 5",
We cannot remove this

2021-05-03 06:29 UTC, arbulu89 commented on powervs/main.tf
> +  hana_cluster_vip           = ""
We should have the auto-generator if the IP addresses here. But this might come in a next PR

2021-05-03 06:29 UTC, arbulu89 commented on powervs/main.tf
> +  authorized_keys                     = []
Why is this empty?

2021-05-03 06:29 UTC, arbulu89 commented on powervs/main.tf
> +  public_key                          = var.pi_key_pair_name
In the other providers this is name `var.public_key`, why do we have a different name here?

2021-05-03 06:29 UTC, arbulu89 commented on powervs/modules/hana_node/main.tf
> +  create_ha_infra             = var.hana_count > 1 && var.common_variables["hana"]["ha_enabled"] ? 1 : 0
You might need to format this file to have a better indenting using `terraform fmt` command in this folder

2021-05-03 06:29 UTC, arbulu89 commented on powervs/modules/hana_node/main.tf
> +  pi_volume_name       = "${terraform.workspace}-${var.name}-volume${count.index + 1}"
We shouldn't use `terraform.workspace` here. We should use `deployment_name`

2021-05-03 06:29 UTC, arbulu89 commented on powervs/modules/hana_node/main.tf
> +  pi_instance_name      = "${terraform.workspace}-${var.name}0${count.index + 1}"
We should use `deployment_name` instead of `terraform.workspace`

2021-05-03 06:29 UTC, arbulu89 commented on salt/hana_node/hana_inst_media.sls
> +  {% if (grains['provider'] == 'libvirt') or (grains['provider'] == 'powervs') %}
Add `powervs` in the list together with `libvirt` and `openstack`

2021-05-03 06:29 UTC, arbulu89 commented on salt/hana_node/mount/powervs.sls
> +{% set hostname = grains['hostname'] %}
You don't need need to have this `hostname` assigment within the loop

2021-05-03 06:29 UTC, arbulu89 commented on salt/hana_node/mount/powervs.sls
> +{%- set wwns = grains['hana_data_disks_wwn'][hostname].split(',') %}
I don't really understand why you get the data with `hostname`. Why are you sending data of other nodes, is this needed?
Maybe you should change the grains creation to only have data of this node

2021-05-03 06:29 UTC, arbulu89 commented on salt/os_setup/init.sls
> +  {% if grains['provider'] == 'libvirt' %}
You cannot add this. It is used by the other providers too

2021-05-03 15:10 UTC, arbulu89 approved these changes
@mfriesenegger As talked in person, PR approved, so we will get a final deep review when the branch gets moved to `Master`

2021-05-03 15:15 UTC, merged

2021-05-06 13:51 UTC, mfriesenegger commented on generic_modules/salt_provisioner/main.tf
> -    bastion_host        = var.bastion_host
This is temporary as I was learning the automation.  I will be enabling and testing the bastion functionality with powervs in a future PR.

2021-05-06 18:57 UTC, mfriesenegger commented on generic_modules/salt_provisioner/main.tf
> -      "${var.reboot} && [ -f /var/run/reboot-needed ] && echo \"Rebooting the machine...\" && (nohup sudo sh -c 'systemctl stop sshd;/sbin/reboot' &) && sleep 5",
I removed /var/run/reboot-needed test condition because it is not implemented in 12 SP4.

2021-05-06 19:00 UTC, mfriesenegger commented on powervs/main.tf
> +  authorized_keys                     = []
IBM Cloud has authorized keys capability for PowerVS which I am currently using.  At this point, I have not needed to test this  authorized_keys variable.

2021-05-06 19:04 UTC, mfriesenegger commented on powervs/main.tf
> +  public_key                          = var.pi_key_pair_name
pi_key_pair_name is a required input parameter - https://cloud.ibm.com/docs/ibm-cloud-provider-for-terraform?topic=ibm-cloud-provider-for-terraform-power-vsi#power-instance.  I did made this change while learning the automation.  I am open to changing this is a future PR.