Move DRBD habootstrap template and notify script of exporter to drbd-formula
SUSE/ha-sap-terraform-deployments pull request #663
Opened 2021-03-17 09:24 UTC by nick-wang

Move the DRBD habootstrap formula template and notify script
of ha exporter to drbd-formula.

Should use together with https://github.com/SUSE/drbd-formula/pull/21, drbd-formula >= 0.4.2

As long as this pull request merged. All changes in habootstrap cluster template should 
change in drbd-formula:templates/habootstrap-formula/cluster_resources_nfs_cloud.j2

2021-03-17 09:38 UTC, arbulu89 requested changes
Thanks @nick-wang Some comments below.
Besides, is the PR removing the whole `files` folder in `drbd_node` folder?

2021-03-17 09:38 UTC, arbulu89 commented on pillar_examples/automatic/drbd/cluster.sls
> +      source: /usr/share/salt-formulas/states/drbd/templates/habootstrap-formula/cluster_resources_nfs_cloud.j2
Let's put `salt://drbd/templates/habootstrap-formula/cluster_resources_nfs_cloud.j2` here.
Here `salt` refers to the root_files we have in the salt configuration file, and `/usr/share/salt-formulas/states` is already there

2021-03-17 09:38 UTC, arbulu89 commented on salt/drbd_node/custom_handlers.sls
> +    - source: /usr/share/salt-formulas/states/drbd/templates/ha_cluster_exporter/notify-split-brain-haclusterexporter-suse-metric.sh
The same for `salt` thing: `salt://drbd/templates/ha_cluster_exporter/notify-split-brain-haclusterexporter-suse-metric.sh`

2021-03-18 08:20 UTC, nick-wang commented on pillar_examples/automatic/drbd/cluster.sls
> +      source: /usr/share/salt-formulas/states/drbd/templates/habootstrap-formula/cluster_resources_nfs_cloud.j2
Thanks, i totally forget this tips.
It looks better to remove the absolute path.

2021-03-18 09:38 UTC, arbulu89 approved these changes
Thanks @nick-wang ,
If you tested (at least in 1 provider) and works go ahead and merge

2021-03-19 01:08 UTC, nick-wang commented
> Thanks @nick-wang ,
> If you tested (at least in 1 provider) and works go ahead and merge

Yes, i tested this with new drbd-formula package on libvirt (against the latest develop) already.
It works as expected, so i will merge them.

Thanks a lot for the review.

2021-03-19 01:14 UTC, merged