[WIP] configure prometheus targets based on host, HA, VIP addresses
SUSE/ha-sap-terraform-deployments pull request #710
Opened 2021-06-15 12:59 UTC by yeoldegrove

This PR introduces:
 - different grains for
   - `netweaver_targets`       --> node addresses
   - `netweaver_targets_ha` --> HA/corosync addresses
   - `netweaver_targets_vip` --> Virtual Addresses of Applications (might be cluster services)
- This corrects the behaviour of `netweaver_targets` which included only the virtual address before.
- It is now easier to distinguish between the different targets for the different prometheus exporters

This PR fixes:
- azure: netweaver''s application VIPs are only reachable via a load-balancer #611 
  - add port 9680 for `sap_host_expoter` to lb
- TODO: TEST: aws: netweaver''s application VIPs are only reachable via route?
- security group fixes for aws/azure/gcp

2021-06-17 07:17 UTC, yeoldegrove commented
I did successful test runs on AWS + Azure.
It should work on GCP, libvirt, openstack too as the changes are basically the same everywhere.

2021-06-18 09:47 UTC, stefanotorresi requested changes
Good changes, but there is something I'm not sure about with the `sap_host_exporter` targets.

2021-06-18 09:47 UTC, stefanotorresi commented on salt/monitoring_srv/prometheus/prometheus.yml.j2
> +        {%- endfor %}
Hmm, I'm not sure about this: unlike `hanadb_exporter`, `sap_host_exporter` is intended to be targeted on all the nodes, regardless of their role in the HA setup.
With this change, we would effectively stop collecting metrics for the ERS, PAS and AAS, which is not desirable.
We can keep the `netweaver_targets_vip` grain for future use, but I guess we don't actually need to use it, unless I'm missing something.

2021-06-18 10:06 UTC, yeoldegrove commented on salt/monitoring_srv/prometheus/prometheus.yml.j2
> +        {%- endfor %}
Here is an example config from a provisioned monitoring node:
```
  - job_name: netweaver
    static_configs:
      - targets:
        - "10.0.3.30:9100" # node_exporter
        - "10.0.4.31:9100" # node_exporter
        - "10.0.3.32:9100" # node_exporter
        - "10.0.4.33:9100" # node_exporter
        - "10.0.3.30:9664" # ha_cluster_exporter
        - "10.0.4.31:9664" # ha_cluster_exporter
        - "192.168.1.30:9680" # sap_host_exporter
        - "192.168.1.31:9680" # sap_host_exporter
        - "192.168.1.32:9680" # sap_host_exporter
        - "192.168.1.33:9680" # sap_host_exporter
```

The grain`netweaver_targets_vip` basically has the old values from `netweaver_targets` ... so nothing really changed in regards to the `sap_host_exporter`.
It has still the 4 VIPs of the actual SAP instances.

2021-06-28 08:35 UTC, arbulu89 requested changes
Hi @yeoldegrove ,
The functionality looks good.
However, I have a change request. Instead of creating all of these variables in each of the individual provides variables, what about adding these target variables to `common_variables`? Eventually, the `common_variables` are passed to the monitoring module, so we could get rid off many duplicated code in the variables files.

2021-06-28 08:35 UTC, arbulu89 commented on aws/main.tf
> +  drbd_targets          = var.drbd_enabled ? local.drbd_ips : []
Do we need these `drbd_targets` and `drbd_targets_ha`? Both have the same values

2021-06-28 08:35 UTC, arbulu89 commented on aws/main.tf
> +  hana_targets_vip      = var.hana_ha_enabled ? [local.hana_cluster_vip] : [local.hana_ips[0]] # we use the vip for HA scenario and 1st hana machine for non HA to target the active hana instance
Even though this will work, the naming will be a bit confusing, because in non HA scenarios the vip shouldn't be used.
Anyway, I guess we can live with this as the comment clarifies what is going on

2021-06-28 08:35 UTC, arbulu89 commented on salt/monitoring_srv/prometheus/prometheus.yml.j2
> +        {%- endfor %}
Yes, the netweaver VIPs are not only attached to clustered nodes, they are set in all nodes

2021-06-28 11:00 UTC, stefanotorresi commented on salt/monitoring_srv/prometheus/prometheus.yml.j2
> +        {%- endfor %}
uh okay, all good then!

2021-06-30 11:25 UTC, yeoldegrove commented on aws/main.tf
> +  hana_targets_vip      = var.hana_ha_enabled ? [local.hana_cluster_vip] : [local.hana_ips[0]] # we use the vip for HA scenario and 1st hana machine for non HA to target the active hana instance
I could not think of a better naming scheme. So it will stay this way until this changes ;)

2021-06-30 11:28 UTC, yeoldegrove commented on aws/main.tf
> +  drbd_targets          = var.drbd_enabled ? local.drbd_ips : []
We do not need it at the moment. It is this way to be consistent in all 3 setups we currently deploy.
Maybe a "DRDB exporter" will come in the future... Who knows.

2021-06-30 11:30 UTC, yeoldegrove commented
> However, I have a change request. Instead of creating all of these variables in each of the individual provides variables, what about adding these target variables to `common_variables`? Eventually, the `common_variables` are passed to the monitoring module, so we could get rid off many duplicated code in the variables files.

@arbulu89 Good idea. This saves a lot of code. I added the variables to `common_variables` now and did a successfull test buildup on azure.

2021-06-30 12:58 UTC, arbulu89 approved these changes
Great @yeoldegrove

2021-07-01 09:46 UTC, stefanotorresi approved these changes

2021-07-01 10:43 UTC, merged