add optional native fencing for microsoft-azure
SUSE/ha-sap-terraform-deployments pull request #714
Opened 2021-06-18 11:31 UTC by yeoldegrove

This adds the possibility to deploy HANA, DRBD, Netweaver Clusters with the native "Azure Fence Agent".

- add documentation
- add new variables and grains to be used by formulas
- make sure `python3-azure-identity` rpm is installed as it is a dependency to run `stonith:fence_azure_arm`

There is still an open PR at https://github.com/ClusterLabs/fence-agents/pull/410 to make `stonith:fence_azure_arm` work with the latest Microsoft API changes. Without this code, the resources will not start.

The actual resources are defined in formulas and this PRs:
https://github.com/SUSE/saphanabootstrap-formula/pull/130
https://github.com/SUSE/drbd-formula/pull/26
https://github.com/SUSE/sapnwbootstrap-formula/pull/87

2021-06-23 06:41 UTC, yeoldegrove commented
https://github.com/ClusterLabs/fence-agents/pull/415 was created to make `stonith:azure_fence_arm` to work with the latest Microsoft API changes.

2021-06-28 08:41 UTC, arbulu89 reviewed
Thanks @yeoldegrove ,
Just a question whether the package installation should go here or in the `habootstrap-formula`

2021-06-28 08:41 UTC, arbulu89 commented on azure/main.tf
> +  subscription_id           = data.azurerm_subscription.current.subscription_id
Could we put a comment on top of these new variables? Saying that they are used only by the azure fence agent

2021-06-28 08:41 UTC, arbulu89 commented on salt/cluster_node/ha/native_fencing.sls
> +python3-azure-identity:
I'm not sure if this pkg installation should go here, or maybe better in the `habootstrap-formula`. We already have some similar package installation for gcp in the formula itself

2021-06-28 15:44 UTC, yeoldegrove commented on azure/main.tf
> +  subscription_id           = data.azurerm_subscription.current.subscription_id
fixed in 80ed2bb

2021-06-28 16:28 UTC, yeoldegrove commented on salt/cluster_node/ha/native_fencing.sls
> +python3-azure-identity:
You are absolutely right.
A better place is here: https://github.com/SUSE/habootstrap-formula/pull/83

2021-06-29 06:47 UTC, arbulu89 commented on salt/cluster_node/ha/native_fencing.sls
> +python3-azure-identity:
I guess we will need to remove completely this file, right?

2021-06-29 06:57 UTC, arbulu89 requested changes
Hi @yeoldegrove ,
As commented in https://github.com/SUSE/sapnwbootstrap-formula/pull/87, we will need to use the grains values to modify the pillar content of the `pillar_examples/automatic` to use the data from the pillar files, and not the grains, as the grains are only used in this project, but the formulas should work standalone

2021-06-29 12:27 UTC, yeoldegrove commented on salt/cluster_node/ha/native_fencing.sls
> +python3-azure-identity:
removed in 8c7c7ec

2021-06-29 15:46 UTC, yeoldegrove commented
> As commented in [SUSE/sapnwbootstrap-formula#87](https://github.com/SUSE/sapnwbootstrap-formula/pull/87), we will need to use the grains values to modify the pillar content of the `pillar_examples/automatic` to use the data from the pillar files, and not the grains, as the grains are only used in this project, but the formulas should work standalone

@arbulu89 pillars are now used instead of grains

2021-06-30 06:25 UTC, arbulu89 approved these changes
Thanks @yeoldegrove

2021-07-02 07:28 UTC, merged