add support for rootdisk as data_disk_type and change default drbd fencing to sbd
SUSE/ha-sap-terraform-deployments pull request #720
Opened 2021-06-30 16:01 UTC by melzer-b1

Deployment failed on using rootdisk as data source.

2021-06-30 16:06 UTC, yeoldegrove requested changes
@melzer-b1 Thanks for adding this!
Could you please add an example line for `rootdisk` in `terraform.tfvars.example`?

2021-06-30 16:55 UTC, melzer-b1 commented
added rootdisk example in terraform.tfvars.example

2021-07-01 06:30 UTC, arbulu89 reviewed
Hi guys,

I found out now that we create a NFS service in the bastion host for openstack. I don't like much this idea, but well, I guess it is fine.

I would suggest to put some comments in the salt code saying that this only applies to openstack

2021-07-05 10:50 UTC, yeoldegrove commented on salt/bastion/init.sls
> +{# 'rootdisk' is used for nfs server on openstack #}
`rootdisk` AND `ephemeral` AND `volume` are only used on openstack.
Maybe rephrase it like "NFS server for `/sapinst` on bastion is only available on openstack." ?

2021-07-05 12:27 UTC, yeoldegrove approved these changes

2021-07-06 06:22 UTC, yeoldegrove commented
@arbulu89 good to merge now from your side?

2021-07-06 06:53 UTC, arbulu89 commented on salt/bastion/sapinst.sls
> +{# NFS server used for '/sapinst' on bastion is only available on openstack. #}
Do we really need this `jinja` kind of comments?
Using simple `# my comment` should work too

2021-07-06 07:01 UTC, arbulu89 commented
> @arbulu89 good to merge now from your side?

Yes. I don't personally like this `jinja` kind of comments (mostly, because the rest of the code uses normal comments).
But it is acceptable of course.
Up to you if you want to change them or not

2021-07-06 08:39 UTC, melzer-b1 commented
My thoughts by using jinja2 comments are: First we can distinguish comments for jinja2 blocks from ordinary salt comments.
Secondary there is a jinja2 feature where you can write a expresion "{% if … }" as "# if …" so i wanted to avoid collisions.
We found some other cases of jinja2 comments in the code base so we decided to use them.

If you think this conflicts to your coding style I can change it to the other type of comment.

2021-07-13 07:58 UTC, merged