make hostnames configurable
SUSE/ha-sap-terraform-deployments pull request #767
Opened 2021-09-30 15:31 UTC by yeoldegrove

This PR makes it possible to configure the hostnames of each VM type via variables in `terraform.tfvars`.
Additonally there is the possibiliy to add the `deployment_name` as a prefix (similar as for GCP at the moment).
``` 
  # Add the "deployment_name" as a prefix to the hostname.
  #deployment_name_in_hostname = false

  #hana_name = "vmhana"
  #iscsi_name = "vmiscsi"
  #monitoring_name = "vmmonitoring"
  #drbd_name = "vmdrbd"
  #netweaver_name = "vmnetweaver"
``` 

- run salt default state on all hosts
4392907
  * needed to actually change hostnames via state `default.hostname`
- ignore terraform lockfiles
e15a184
- ignore gcp credentials
83ab6a9
- azure: make hostnames configurable
a91e395
- aws: make hostnames configurable
e0f333c
- gcp: make hostnames configurable
fbdff1b
- libvirt: make hostnames configurable
98b3815

2021-10-01 05:58 UTC, arbulu89 requested changes
Hey @yeoldegrove,

One important consideration.
I have seen that you have remove the workspace part from gcp, aws, libvirt resources name.
I'm not sure if we can do that.
The thing if we do that, we most probably are not going to be able to have multiple deployments in one subscription/user, and as the name would conflict.

That's why we added the workspace, to have the option to easily prefix the resources on these places. In azure, we have the advantage of the resource groups, what doesn't exist in the others.

I'm afraid you will need to revert this back.

With this, what we could do is to make the `deployment_name` a mandatory value, and remove any default option. We should always know who is the owner of the deployment

2021-10-01 05:58 UTC, arbulu89 commented on aws/variables.tf
>    type        = string
Shouldn't we have a default value here? `vmhana`

2021-10-01 05:58 UTC, arbulu89 commented on aws/modules/hana_node/variables.tf
> +variable "network_domain" {
I'm sure now, but is the `network_domain` used in the cloud providers? Can you check if this variable executes something on salt in these scenarios?
Maybe we can even remove it

2021-10-01 05:58 UTC, arbulu89 commented on azure/modules/drbd_node/variables.tf
> +  type    = string
Let's add the description

2021-10-01 05:58 UTC, arbulu89 commented on azure/modules/hana_node/variables.tf
> +  type    = string
Description

2021-10-01 07:45 UTC, yeoldegrove commented on aws/modules/hana_node/variables.tf
> +variable "network_domain" {
As far as I can tell `network_domain` is only used here to set the FQDN hostname: https://github.com/SUSE/ha-sap-terraform-deployments/blob/619c50f66436282e479823ddb8526f52700cf3dd/salt/default/hostname.sls#L31

This might be an important option in some customer cases. Even different domains per VM type might be a use case. This is why I built it to be set on a per module level.
I forgot to extend it so that one can set it from `terraform.tfvars` on a global and VM type level.
@arbulu89  Are you ok with this?

2021-10-01 07:47 UTC, arbulu89 commented on aws/modules/hana_node/variables.tf
> +variable "network_domain" {
If it is useful for the users and we still have the default value, it is totally fine for me

2021-10-01 07:48 UTC, yeoldegrove commented on aws/variables.tf
>    type        = string
Will be fixed.

2021-10-01 07:48 UTC, yeoldegrove commented on azure/modules/drbd_node/variables.tf
> +  type    = string
Will be added everywhere.

2021-10-01 07:48 UTC, yeoldegrove commented on azure/modules/hana_node/variables.tf
> +  type    = string
Will be added everywhere.

2021-10-01 09:56 UTC, yeoldegrove commented
@arbulu89 I get the point about the workspace and deployment_name prefixing in the resources...
The intention was not to change this behavior, will rework it.

I plan to built it in a way that the resource names stay the same as now and you can only decide if you want to have the deployment_name as a prefix to the actual hostname (within salt/OS, not terraform).

2021-10-01 10:49 UTC, arbulu89 commented
> @arbulu89 I get the point about the workspace and deployment_name prefixing in the resources... The intention was not to change this behavior, will rework it.
> 
> I plan to built it in a way that the resource names stay the same as now and you can only decide if you want to have the deployment_name as a prefix to the actual hostname (within salt/OS, not terraform).

I don't know if there is a way to use resources with the same name. Maybe using tags or similar.

2021-10-06 06:52 UTC, yeoldegrove commented
@arbulu89 please re-review.

2021-10-06 12:02 UTC, arbulu89 requested changes
@yeoldegrove Just a small request.
I would put the `deployment_name_in_hostname` variable default value to true in `aws`, `gcp` and `libvirt`, and leave it to false in `azure`.
Not having the deployment name should be the edge case.

2021-10-06 12:32 UTC, yeoldegrove commented on aws/variables.tf
> +  default     = false
@arbulu89 fixed

2021-10-06 13:05 UTC, merged