add HANA scale-out deployments for AWS/GCP/libvirt/openstack
SUSE/ha-sap-terraform-deployments pull request #846
Opened 2022-04-29 15:17 UTC by yeoldegrove

## prerequisites
* needs commits from #845 
* needs https://github.com/SUSE/shaptools/pull/70
* needs https://github.com/SUSE/salt-shaptools/pull/88

## features
* add HANA scale-out deployments for AWS/GCP/libvirt
  * AWS -> on shared EFS storage
    * https://docs.aws.amazon.com/sap/latest/sap-hana/operating-system-and-storage-configuration.html
    * https://documentation.suse.com/sbp/all/html/SLES-SAP-hana-scaleOut-PerfOpt-12-AWS/index.html
  * GCP -> on shared filestore storage
    * https://cloud.google.com/solutions/sap/docs/sap-hana-ha-scaleout-deployment-guide
    * https://cloud.google.com/filestore/docs/creating-instances
  * libvirt -> on shared NFS storage

2022-05-02 13:58 UTC, melzer-b1 commented on aws/terraform.tfvars.example
> +# see https://docs.microsoft.com/en-us/azure/virtual-machines/workloads/sap/hana-vm-operations-netapp
this is an AWS example

2022-05-02 14:19 UTC, yeoldegrove commented on aws/terraform.tfvars.example
> +# see https://docs.microsoft.com/en-us/azure/virtual-machines/workloads/sap/hana-vm-operations-netapp
fixed and force pushed

2022-05-02 15:16 UTC, melzer-b1 requested changes

2022-05-02 15:16 UTC, melzer-b1 commented on openstack/README.md
> +The first parameter `disks_size` is used to provision the resourcen in terraform. One disk is using one entry. Every further disk is added by appending more comma separated entries to each parameter.
resources

2022-05-02 15:16 UTC, melzer-b1 commented on aws/README.md
> +The first two parameters `disks_type` and `disks_size` are used to provision the resourcen in terraform. One disk is using one entry. Every further disk is added by appending more comma separated ent
resources

2022-05-02 16:28 UTC, yeoldegrove commented on openstack/README.md
> +The first parameter `disks_size` is used to provision the resourcen in terraform. One disk is using one entry. Every further disk is added by appending more comma separated entries to each parameter.
fixed

2022-05-02 16:29 UTC, yeoldegrove commented on libvirt/modules/majority_maker_node/salt_provisioner.tf
> +      "if which cloud-init; then cloud-init status --wait; else echo no cloud-init installed; fi"
fixed

2022-05-02 16:29 UTC, yeoldegrove commented on openstack/README.md
> +The first parameter `disks_size` is used to provision the resourcen in terraform. One disk is using one entry. Every further disk is added by appending more comma separated entries to each parameter.
will be fixed in #845

2022-05-02 16:29 UTC, yeoldegrove commented on aws/README.md
> +The first two parameters `disks_type` and `disks_size` are used to provision the resourcen in terraform. One disk is using one entry. Every further disk is added by appending more comma separated ent
will be fixed in #845

2022-05-03 11:21 UTC, melzer-b1 approved these changes

2022-05-24 12:27 UTC, merged