Libvirt documentation enhancements
SUSE/ha-sap-terraform-deployments pull request #861
Opened 2022-05-27 08:46 UTC by mr-stringer

2022-05-30 07:16 UTC, yeoldegrove requested changes
I really like the additions but have some suggestions on WHERE to put them.
Also some other things to clear up.

2022-05-30 07:16 UTC, yeoldegrove commented on libvirt/README.md
> +This sub directory contains the cloud specific part for usage of this repository with libvirt. Looking for another provider? See [Getting started](../README.md#getting-started).
This general layout of the README's for every cloud provider are the same.
So if you change something here, please also change it in the other README's.

2022-05-30 07:16 UTC, yeoldegrove commented on libvirt/README.md
> +## Requirements
This is the intended hierarchy, what speaks against it?
Again...would have to be changed in every other README.

2022-05-30 07:16 UTC, yeoldegrove commented on libvirt/README.md
> +## Quickstart
see comment about hierarchy

2022-05-30 07:16 UTC, yeoldegrove commented on libvirt/README.md
> +## High-level description
see comment about hierarchy. Name change is fine.

2022-05-30 07:16 UTC, yeoldegrove commented on libvirt/README.md
> +## Customization
see comment about hierarchy

2022-05-30 07:16 UTC, yeoldegrove commented on libvirt/README.md
> +## Advanced Customization
see comment about hierarchy

2022-05-30 07:16 UTC, yeoldegrove commented on libvirt/README.md
> +### Terraform Parallelism
see comment about hierarchy

2022-05-30 07:16 UTC, yeoldegrove commented on libvirt/README.md
> +## Troubleshooting
see comment about hierarchy

2022-05-30 07:16 UTC, yeoldegrove commented on libvirt/README.md
> +  For libvirt based configurations, the code uses SBD as the STONITH method for clustering.  The SBD disk is created in the storage pool and therefore iSCSI is not required.  When configuring the ter
How about we let we let the Quickstart section mostly untouched and move provider specific settings to Requirements?
This would make the Quickstart section easier to maintain (again...other cloud providers look the same).

2022-05-30 07:16 UTC, yeoldegrove commented on libvirt/README.md
> +  ```
see above... move to requirements?

2022-05-30 07:16 UTC, yeoldegrove commented on libvirt/README.md
> +  If this error occurs, simple re-run `terraform apply` after ~30 seconds.
move to troubleshooting?

2022-05-30 10:33 UTC, mr-stringer commented on libvirt/README.md
> +  For libvirt based configurations, the code uses SBD as the STONITH method for clustering.  The SBD disk is created in the storage pool and therefore iSCSI is not required.  When configuring the ter
Moved to Requirements

2022-05-30 10:33 UTC, mr-stringer commented on libvirt/README.md
> +  ```
Done

2022-05-30 10:33 UTC, mr-stringer commented on libvirt/README.md
> +  If this error occurs, simple re-run `terraform apply` after ~30 seconds.
Done

2022-05-30 10:34 UTC, mr-stringer commented on libvirt/README.md
> +## Troubleshooting
Done

2022-05-30 10:34 UTC, mr-stringer commented on libvirt/README.md
> +## Customization
Done

2022-05-30 10:34 UTC, mr-stringer commented on libvirt/README.md
> +## Requirements
Reverted

2022-05-30 10:34 UTC, mr-stringer commented
Updated as requested

2022-06-09 11:24 UTC, yeoldegrove approved these changes
Corrected a few details.
Otherwise, great work :+1:

2022-06-09 12:00 UTC, merged